// <auto-generated />
using System;
using CarsWebApp.DbAcces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarsWebApp.Migrations
{
    [DbContext(typeof(MyCarsDbContext))]
    [Migration("20241013213014_FirstCreate")]
    partial class FirstCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyDomain.Car", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("CarColorId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarColorId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Chevrolet",
                            CarColorId = 5,
                            Price = 50000,
                            Type = "Camaro",
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Hyundai",
                            CarColorId = 3,
                            Price = 20000,
                            Type = "Elantra",
                            Year = 2022
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Volkswagen",
                            CarColorId = 3,
                            Price = 30000,
                            Type = "Passat",
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Chevrolet",
                            CarColorId = 4,
                            Price = 28000,
                            Type = "Equinox",
                            Year = 2022
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Volkswagen",
                            CarColorId = 2,
                            Price = 27000,
                            Type = "Jetta",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("MyDomain.CarColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("CarColors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Blue"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Black"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Gold"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Silver"
                        });
                });

            modelBuilder.Entity("MyDomain.Car", b =>
                {
                    b.HasOne("MyDomain.CarColor", "CarColor")
                        .WithMany("Cars")
                        .HasForeignKey("CarColorId");

                    b.Navigation("CarColor");
                });

            modelBuilder.Entity("MyDomain.CarColor", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
